# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18EirNregNTpkv60QkAtYRHYVhb-4bkjh
"""

print("hello world")

print(" software \n civil \n machanical \n food sience")

num1= 15
num2= 20
print(num1+num2)

num1=15
num2+20
addition = num1+num2
addition

substact = num1-num2
substact

multiply = num1*num2
multiply

divide = num1/num2
divide

num1 = int(input("Enter first value"))
num2 = int(input("enter second value"))
addition = num1 + num2
print(addition)

print("--------Mini Calculator")

num1 = float(input("enter 1st value"))
num2 = float(input("enter 2nd value"))

print("1: addtion \n 2: substraction \n 3: division \n multiplication ")

addition = num1 + num2
substaction = num1 - num2
division = num1 / num2
multiplcation = num1 * num2

choice = int(input("Enter 1 till 4: "))

if choice == 1:
    print(addition)
elif choice == 2:
    print(substraction)
elif choice == 3:
    print(division)
elif choice == 4:
    print(multiplication)

else:
    print("invalid input")

print("--------Mini Calculator--------")

num1 = float(input("enter 1st value"))
num2 = float(input("enter 2nd value"))

print("1: addtion \n 2: substraction \n 3: division \n multiplication ")

addition = num1 + num2
substraction = num1 - num2
division = num1 / num2
multiplication = num1 * num2

choice = int(input("Enter 1 till 4: "))

if choice == 1:
    print(addition)

elif choice == 2:
    print(substraction)

elif choice == 3:
    print(division)

elif choice == 4:
    print(multiplication)

else:
    print("invalid input")

print("--------Bio-Data--------")
num1=input(str("enter your first name"))
num2=input(str("enter your middle name"))
num3=input(str("enter your last name"))

print(num1,num2,num3)